/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cursor_hand_h_
#define _cursor_hand_h_
//---------------------------------------------------------------------------------
extern const unsigned char cursor_hand[];
extern const int cursor_hand_size;
//---------------------------------------------------------------------------------
#endif //_cursor_hand_h_
//---------------------------------------------------------------------------------
