/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cursor_grab_h_
#define _cursor_grab_h_
//---------------------------------------------------------------------------------
extern const unsigned char cursor_grab[];
extern const int cursor_grab_size;
//---------------------------------------------------------------------------------
#endif //_cursor_grab_h_
//---------------------------------------------------------------------------------
