/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _google_satellite_h_
#define _google_satellite_h_
//---------------------------------------------------------------------------------
extern const unsigned char google_satellite[];
extern const int google_satellite_size;
//---------------------------------------------------------------------------------
#endif //_google_satellite_h_
//---------------------------------------------------------------------------------
