/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _google_maps_h_
#define _google_maps_h_
//---------------------------------------------------------------------------------
extern const unsigned char google_maps[];
extern const int google_maps_size;
//---------------------------------------------------------------------------------
#endif //_google_maps_h_
//---------------------------------------------------------------------------------
