/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _google_terrain_h_
#define _google_terrain_h_
//---------------------------------------------------------------------------------
extern const unsigned char google_terrain[];
extern const int google_terrain_size;
//---------------------------------------------------------------------------------
#endif //_google_terrain_h_
//---------------------------------------------------------------------------------
