/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _live_satellite_h_
#define _live_satellite_h_
//---------------------------------------------------------------------------------
extern const unsigned char live_satellite[];
extern const int live_satellite_size;
//---------------------------------------------------------------------------------
#endif //_live_satellite_h_
//---------------------------------------------------------------------------------
