/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _live_hybrid_h_
#define _live_hybrid_h_
//---------------------------------------------------------------------------------
extern const unsigned char live_hybrid[];
extern const int live_hybrid_size;
//---------------------------------------------------------------------------------
#endif //_live_hybrid_h_
//---------------------------------------------------------------------------------
