/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _openstreetmap_h_
#define _openstreetmap_h_
//---------------------------------------------------------------------------------
extern const unsigned char openstreetmap[];
extern const int openstreetmap_size;
//---------------------------------------------------------------------------------
#endif //_openstreetmap_h_
//---------------------------------------------------------------------------------
